### ISSUE TITLE
Problem running Maintenance.deployReleaseCandidates()

### ISSUE THREAD

**Issue by zepumph** [phetsims/perennial#130]
While working on the maintenance release for https://github.com/phetsims/chipper/issues/746, I have run into an issue. 

So far @mattpen has been driving, and we have completed `Maintenance.updateDependencies()` on his machine. He then gave me the `.maintenance.json` file, which I put in the root of perennial.
Then I tried to deploy the rcs and the following error occurred:
```
 Michael ~/PHET/git/perennial (master)
 $ grunt maintenance
Running "maintenance" task
maintenance> Maintenance.deployReleaseCandidates()
Running RC deploy for acid-base-solutions 1.2
>> Detected failure during deploy, reverting to master
Maintenance task failed:
Error: Failure with RC deploy for acid-base-solutions to 1.2: Error: grunt.cmd lint-all clean build --brand=phet --locales=en --allHTML --debugHTML in ../acid-base-solutions failed with exit code 6 and stdout:
Running "eslint:allFiles" (eslint) task
Warning: Cannot read config file: C:\Users\Michael\PHET\git\chipper\eslint\.eslintrc.js
Error: Cannot find module 'C:\Users\Michael\PHET\git\chipper\eslint\.eslintrc.js'
Referenced from: C:\Users\Michael\PHET\git\.eslintrc.js Use --force to continue.

Aborted due to warnings.

  at Function.deployReleaseCandidates (C:\Users\Michael\PHET\git\perennial\js\common\Maintenance.js:717:17)
  at process._tickCallback (internal/process/next_tick.js:68:7)

Full Error details:
{}

```

@jonathanolson I thought you had fixed this error in a prior maintenance release, so I thought I would reach out to you before investigating myself. What do you think? Matching priority of the original issue.

**Comment by zepumph** [comment]
Oh my goodness! I'm sorry about this issue. After looking further at the errors above,  it seems like having an eslintrc.js file in the root of my git repos directory was causing the issue. The task is now running. Closing
