### ISSUE TITLE
CT phetioAPIChangeCheck is assigned a value but never used

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/perennial#183]
```
perennial : lint
Lint failed with status code 1:
[4mRunning "lint" task[24m
[31mFatal error: Perennial task failed:
Error: grunt lint --repo=perennial in ../chipper failed with exit code 1 and stdout:
Running "lint" task

/data/share/phet/continuous-testing/ct-snapshots/1592299271739/perennial/js/grunt/production.js
31:7 error 'phetioAPIChangeCheck' is assigned a value but never used no-unused-vars

✖ 1 problem (1 error, 0 warnings)
Fatal error: 1 Lint Errors

at ChildProcess.process.on.code (/data/share/phet/continuous-testing/ct-snapshots/1592299271739/perennial/js/common/execute.js:71:17)
at ChildProcess.emit (events.js:198:13)
at ChildProcess.EventEmitter.emit (domain.js:448:20)
at maybeClose (internal/child_process.js:982:16)
at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)

Full Error details:
{
"cmd": "grunt",
"args": [
"lint",
"--repo=perennial"
],
"cwd": "../chipper",
"stdout": "Running \"lint\" task\n\n/data/share/phet/continuous-testing/ct-snapshots/1592299271739/perennial/js/grunt/production.js\n 31:7 error 'phetioAPIChangeCheck' is assigned a value but never used no-unused-vars\n\n✖ 1 problem (1 error, 0 warnings)\nFatal error: 1 Lint Errors\u0007\n",
"stderr": "",
"code": 1
}[39m
Snapshot from 6/16/2020, 3:21:11 AM

----------------------------------

perennial : lint-everything
Lint-everything failed with status code 1:
[4mRunning "lint-everything" task[24m

/data/share/phet/continuous-testing/ct-snapshots/1592299271739/perennial/js/grunt/production.js
31:7 error 'phetioAPIChangeCheck' is assigned a value but never used no-unused-vars

/data/share/phet/continuous-testing/ct-snapshots/1592299271739/rosetta/js/getRosettaConfig.js
166:7 error 'config' is never reassigned. Use 'const' instead prefer-const

✖ 2 problems (2 errors, 0 warnings)
1 error and 0 warnings potentially fixable with the `--fix` option.
Fatal error: 2 Lint Errors
Snapshot from 6/16/2020, 3:21:11 AM
```

**Comment by zepumph** [comment]
Thanks! This has been fixed.
