### ISSUE TITLE
CT Error: grunt lint repo=perennial in ../chipper failed with exit code 1 and stdout:

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/perennial#194]
```
perennial : lint
Lint failed with status code 1:
[4mRunning "lint" task[24m
[31mFatal error: Perennial task failed:
Error: grunt lint --repo=perennial in ../chipper failed with exit code 1 and stdout:
Running "lint" task

/data/share/phet/continuous-testing/ct-snapshots/1597907801873/perennial/js/build-server/deployImages.js
41:13 error 'brand' is never reassigned. Use 'const' instead prefer-const
49:17 error 'file' is never reassigned. Use 'const' instead prefer-const
82:18 error Strings must use singlequote quotes
103:23 error 'project' is never reassigned. Use 'const' instead prefer-const
104:25 error 'simulation' is never reassigned. Use 'const' instead prefer-const

✖ 5 problems (5 errors, 0 warnings)
5 errors and 0 warnings potentially fixable with the `--fix` option.
Fatal error: 5 Lint Errors

at ChildProcess.process.on.code (/data/share/phet/continuous-testing/ct-snapshots/1597907801873/perennial/js/common/execute.js:71:17)
at ChildProcess.emit (events.js:198:13)
at ChildProcess.EventEmitter.emit (domain.js:448:20)
at maybeClose (internal/child_process.js:982:16)
at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
Full Error details:
{
"cmd": "grunt",
"args": [
"lint",
"--repo=perennial"
],
"cwd": "../chipper",
"stdout": "Running \"lint\" task\n\n/data/share/phet/continuous-testing/ct-snapshots/1597907801873/perennial/js/build-server/deployImages.js\n 41:13 error 'brand' is never reassigned. Use 'const' instead prefer-const\n 49:17 error 'file' is never reassigned. Use 'const' instead prefer-const\n 82:18 error Strings must use singlequote quotes\n 103:23 error 'project' is never reassigned. Use 'const' instead prefer-const\n 104:25 error 'simulation' is never reassigned. Use 'const' instead prefer-const\n\n✖ 5 problems (5 errors, 0 warnings)\n 5 errors and 0 warnings potentially fixable with the `--fix` option.\nFatal error: 5 Lint Errors\u0007\n",
"stderr": "",
"code": 1
}[39m
Snapshot from 8/20/2020, 1:16:41 AM

----------------------------------

perennial : lint-everything
Lint-everything failed with status code 1:
[4mRunning "lint-everything" task[24m

/data/share/phet/continuous-testing/ct-snapshots/1597907801873/perennial/js/build-server/deployImages.js
41:13 error 'brand' is never reassigned. Use 'const' instead prefer-const
49:17 error 'file' is never reassigned. Use 'const' instead prefer-const
82:18 error Strings must use singlequote quotes
103:23 error 'project' is never reassigned. Use 'const' instead prefer-const
104:25 error 'simulation' is never reassigned. Use 'const' instead prefer-const

✖ 5 problems (5 errors, 0 warnings)
5 errors and 0 warnings potentially fixable with the `--fix` option.
Fatal error: 5 Lint Errors
Snapshot from 8/20/2020, 1:16:41 AM
```

**Comment by chrisklus** [comment]
Fix pushed above, closing.
