### ISSUE TITLE
ratio-and-proportion failed deploy of 1.0.0

### ISSUE THREAD

**Issue by mattpen** [phetsims/perennial#222]
```
(node:24111) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of undefined
    at parseScreenNames (/data/share/phet/phet-repos/perennial/js/build-server/parseScreenNames.js:40:55)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async module.exports (/data/share/phet/phet-repos/perennial/js/build-server/createTranslationsXML.js:61:23)
```

This failed because we had a dependency on the simulation metadata before the call to syncronize the project.  I removed this dependency, instead drawing the list of locales from the available files in babel.  This is now identical to how we determine the locales for the titles of the sims, so it should work nicely.

**Comment by mattpen** [comment]
I confirmed that this fixed the issue with a manual deploy of the translation XML, fix is pending confirmation from @zepumph that the RAP redeploy goes well.

**Comment by mattpen** [comment]
@zepumph confirmed this worked in Slack. Closing.
