### ISSUE TITLE
Maintenance deleted dependencies.json

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/perennial#226]
https://github.com/phetsims/molecule-polarity/commit/09adee21470b21cf6ef01d94b280af588071d3ff was committed by the automated maintenance process, notably:

```
Checked out molecule-polarity 1.0
Branch molecule-polarity-1.0 does not exist in phetmarks, creating.
Running "lint-all" task

Running "clean" task

Running "lint-all" task

Running "clean" task

Running "requirejs-build" task

Running "after-requirejs-build" task

Done.

Maintenance task failed:
Error: Failure updating dependencies for molecule-polarity to 1.0: Error: git checkout master in ../molecule-polarity failed with exit code 1 and stdout:

    at Function.updateDependencies (C:\Users\olson\phet\git\perennial\js\common\Maintenance.js:803:17)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Full Error details:
{}
```

because there was content on dependencies.json:

```
olson@colors MINGW64 ~/phet/git/molecule-polarity (1.0)
$ git status
On branch 1.0
Your branch is up to date with 'origin/1.0'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   dependencies.json

no changes added to commit (use "git add" and/or "git commit -a")
```

Looks like the updateDependenciesJSON somehow... committed an empty file, and then left an unstaged file?

**Comment by jonathanolson** [comment]
Likely an IDE caused something?
