### ISSUE TITLE
CT perennial task failed (quake)

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/perennial#254]
Seems to be connected to quake
```
perennial : lint-everything
Lint-everything failed with status code 1:
Running "lint-everything" task
Fatal error: Perennial task failed:
Error: Failed to load config "@ljharb" to extend from.
Referenced from: /data/share/phet/continuous-testing/ct-snapshots/1639018530900/quake/node_modules/extend/.eslintrc
at configInvalidError (/data/share/phet/continuous-testing/ct-snapshots/1639018530900/chipper/node_modules/@eslint/eslintrc/lib/config-array-factory.js:290:9)
at ConfigArrayFactory._loadExtendedShareableConfig (/data/share/phet/continuous-testing/ct-snapshots/1639018530900/chipper/node_modules/@eslint/eslintrc/lib/config-array-factory.js:883:23)
at ConfigArrayFactory._loadExtends (/data/share/phet/continuous-testing/ct-snapshots/1639018530900/chipper/node_modules/@eslint/eslintrc/lib/config-array-factory.js:781:25)
at ConfigArrayFactory._normalizeObjectConfigDataBody (/data/share/phet/continuous-testing/ct-snapshots/1639018530900/chipper/node_modules/@eslint/eslintrc/lib/config-array-factory.js:720:25)
at _normalizeObjectConfigDataBody.next (<anonymous>)
at ConfigArrayFactory._normalizeObjectConfigData (/data/share/phet/continuous-testing/ct-snapshots/1639018530900/chipper/node_modules/@eslint/eslintrc/lib/config-array-factory.js:665:20)
at _normalizeObjectConfigData.next (<anonymous>)
at ConfigArrayFactory.loadInDirectory (/data/share/phet/continuous-testing/ct-snapshots/1639018530900/chipper/node_modules/@eslint/eslintrc/lib/config-array-factory.js:511:28)
at CascadingConfigArrayFactory._loadConfigInAncestors (/data/share/phet/continuous-testing/ct-snapshots/1639018530900/chipper/node_modules/@eslint/eslintrc/lib/cascading-config-array-factory.js:379:46)
at CascadingConfigArrayFactory.getConfigArrayForFile (/data/share/phet/continuous-testing/ct-snapshots/1639018530900/chipper/node_modules/@eslint/eslintrc/lib/cascading-config-array-factory.js:300:18)
Full Error details:
Error: Failed to load config "@ljharb" to extend from.
Referenced from: /data/share/phet/continuous-testing/ct-snapshots/1639018530900/quake/node_modules/extend/.eslintrc
Snapshot from 12/8/2021, 7:55:30 PM
```

**Comment by jbphet** [comment]
It looks like `node_modules` is being linted here, but I don't know why.  I committed a specific ignore directive (see the commit above), and that fixed the problem for me locally.  I'll follow up with CT to make sure it's passing.  But the question is: Why is this necessary at all?  Why isn't `node_modules` being ignored here by default?

@zepumph and @samreid - Do either of you know what I need to do to set this up more correctly?

**Comment by jbphet** [comment]
I just checked, and the perennial repo does indeed appear to be fixed on CT.

**Comment by zepumph** [comment]
This seems weird. There is no manual exclusion of node_modules in the project thus far. Presumably the linter is set up to automatically ignore that directory. I decided to be explicit across the project though just to be safe, and removed your sim-specific commit. `node_modules` should forever be ignored now, can you confirm on your side what you can?

**Comment by jbphet** [comment]
Both the local `grunt lint` and `grunt lint-everything` from perennial seem to work fine with this change.  Looks good to me!  Thanks @zepumph - closing.

**Comment by jonathanolson** [comment]
Reopening this, as I'll need to maintenance release to get some branches to build (e.g. BASE 1.5)

**Comment by jbphet** [comment]
@jonathanolson - You reopened this, and it's assigned to me, but I think you're using it as a place to log commits.  I'm assigning it to you, let me know if you think there is something I need to do here.

**Comment by jonathanolson** [comment]
Apologies! Nothing to do here, I'll close after maintenance.

**Comment by jonathanolson** [comment]
Handled in maintenance, closing.
