### ISSUE TITLE
RC deploy fails with "Cannot find module ‘acorn’"

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/perennial#266]
I attempted to publish Geometric Optics 1.1.0-rc.3, using `grunt rc --branch=1.1 --brands=phet`. Build server sent me an email reporting failure: `Cannot find module 'acorn'`.   The abbreviated email that I received is shown below. (I removed several hundred TypeScript compilation lines.)

The local build step in `grunt rc --branch=1.1 --brands=phet` worked fine, and I was able to run & test the sim before proceeding with deploy.

Assigning to @samreid since he replied in Slack with:
> There is a chipper issue assigned to me about doing maintenance to revert acorn bugs.

```
Build failure: Error: Build aborted, Error: grunt --allHTML --debugHTML --brands=phet --locales=en in ../geometric-optics failed with exit code 1
stdout:
Running “lint-all” task
Running “report-media” task
Running “clean” task
Running “build” task
TypeScript compilation complete: 27783ms
6:52:19 AM, 101 ms: ../axon/js/BooleanProperty.ts
6:52:19 AM, 19 ms: ../axon/js/BooleanPropertyTests.js
6:52:19 AM, 66 ms: ../axon/js/DerivedProperty.ts
6:52:19 AM, 42 ms: ../axon/js/DynamicProperty.ts
6:52:19 AM, 24 ms: ../axon/js/Emitter.ts
6:52:19 AM, 13 ms: ../axon/js/EmitterIOTests.js
6:52:19 AM, 29 ms: ../axon/js/EmitterTests.ts
…
6:52:38 AM, 10 ms: ../utterance-queue/js/main.js
6:52:38 AM, 6 ms: ../utterance-queue/js/responseCollector.js
6:52:38 AM, 6 ms: ../utterance-queue/js/utterance-queue-tests.js
Building runnable repository (geometric-optics, brands: phet)
Building brand: phet
Fatal error: Perennial task failed:
Error: Cannot find module ‘acorn’
Require stack:
- /data/share/phet/build-server/chipper/node_modules/acorn-import-assertions/lib/index.js
- /data/share/phet/build-server/chipper/node_modules/webpack/lib/javascript/JavascriptParser.js
- /data/share/phet/build-server/chipper/node_modules/webpack/lib/javascript/JavascriptModulesPlugin.js
- /data/share/phet/build-server/chipper/node_modules/webpack/lib/WebpackOptionsApply.js
- /data/share/phet/build-server/chipper/node_modules/webpack/lib/webpack.js
- /data/share/phet/build-server/chipper/node_modules/webpack/lib/index.js
- /data/share/phet/build-server/chipper/js/grunt/webpackBuild.js
- /data/share/phet/build-server/chipper/js/grunt/buildStandalone.js
- /data/share/phet/build-server/chipper/js/grunt/Gruntfile.js
- /data/share/phet/build-server/geometric-optics/Gruntfile.js
- /data/share/phet/build-server/geometric-optics/node_modules/grunt/lib/grunt/task.js
- /data/share/phet/build-server/geometric-optics/node_modules/grunt/lib/grunt.js
- /home/phet-admin/.nvm/versions/node/v14.18.2/lib/node_modules/grunt-cli/bin/grunt
  at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
  at Function.Module._load (internal/modules/cjs/loader.js:746:27)
  at Module.require (internal/modules/cjs/loader.js:974:19)
  at require (internal/modules/cjs/helpers.js:93:18)
  at Object.<anonymous> (/data/share/phet/build-server/chipper/node_modules/acorn-import-assertions/lib/index.js:8:38)
  at Module._compile (internal/modules/cjs/loader.js:1085:14)
  at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
  at Module.load (internal/modules/cjs/loader.js:950:32)
  at Function.Module._load (internal/modules/cjs/loader.js:790:12)
  at Module.require (internal/modules/cjs/loader.js:974:19)
Full Error details:
Error: Cannot find module ‘acorn’
Require stack:
- /data/share/phet/build-server/chipper/node_modules/acorn-import-assertions/lib/index.js
- /data/share/phet/build-server/chipper/node_modules/webpack/lib/javascript/JavascriptParser.js
- /data/share/phet/build-server/chipper/node_modules/webpack/lib/javascript/JavascriptModulesPlugin.js
- /data/share/phet/build-server/chipper/node_modules/webpack/lib/WebpackOptionsApply.js
- /data/share/phet/build-server/chipper/node_modules/webpack/lib/webpack.js
- /data/share/phet/build-server/chipper/node_modules/webpack/lib/index.js
- /data/share/phet/build-server/chipper/js/grunt/webpackBuild.js
- /data/share/phet/build-server/chipper/js/grunt/buildStandalone.js
- /data/share/phet/build-server/chipper/js/grunt/Gruntfile.js
- /data/share/phet/build-server/geometric-optics/Gruntfile.js
- /data/share/phet/build-server/geometric-optics/node_modules/grunt/lib/grunt/task.js
- /data/share/phet/build-server/geometric-optics/node_modules/grunt/lib/grunt.js
- /home/phet-admin/.nvm/versions/node/v14.18.2/lib/node_modules/grunt-cli/bin/grunt
Sim = geometric-optics Version = 1.1.0-rc.3 Brands = phet Locales = en Shas = {“comment”:“# geometric-optics 1.1.0-rc.3 Tue Apr 05 2022 06:47:57 GMT-0600 (Mountain Daylight Time)“,”assert”:{“sha”:“767b2f345518ceca5144a152ecf40cd4f9206136",“branch”:“HEAD”},“axon”:{“sha”:“cde0db2642ee711a9a8492cfe6a5a51fdb7e1f07”,“branch”:“HEAD”},“brand”:{“sha”:“abb2576ef6eb66541c6ff4524ab510e82e90303d”,“branch”:“HEAD”},“chipper”:{“sha”:“0a2ea7879c37d4860fe7400207c1f8b762d72e18”,“branch”:“HEAD”},“dot”:{“sha”:“a3e2bde6e10ac20a3680c26a5e0e47e93ab3cfe6",“branch”:“HEAD”},“geometric-optics”:{“sha”:“de26c34fff3af5e67f0581f0f1e35448a803b7fa”,“branch”:“1.1”},“joist”:{“sha”:“1709c355d5bb4ffa7f29b284237498efc00f0b0e”,“branch”:“HEAD”},“kite”:{“sha”:“669baf6bb0f0c88606a5901c281f3c18a1235f5e”,“branch”:“HEAD”},“perennial-alias”:{“sha”:“31eb501affeb42071074007e39d770a673c86f88",“branch”:“HEAD”},“phet-core”:{“sha”:“e599871127c58347e1f5fa3f44c668b7543e9b73”,“branch”:“HEAD”},“phet-io”:{“sha”:“390450db1801b8cbb13a8669f00a89e46feb000b”,“branch”:“HEAD”},“phet-io-client-guides”:{“sha”:“a73233e690e15ebafed9911ae03aa58edc241297”,“branch”:“HEAD”},“phet-io-wrappers”:{“sha”:“9e71700694b1d1749c98a79261954683e11de846",“branch”:“HEAD”},“phetcommon”:{“sha”:“76fdc36cd68167c7fc8d10a282539e3c77a0cf99”,“branch”:“HEAD”},“phetmarks”:{“sha”:“e75ceb1f5485f7fa5fd1ee84fd0c63a9f0344edb”,“branch”:“HEAD”},“query-string-machine”:{“sha”:“5f3fe34cc9b42ce43af8c1e3e4a03f7a7fff9b54”,“branch”:“HEAD”},“scenery”:{“sha”:“71923dbc172d5802919954ee94b7e4780ee4ebcc”,“branch”:“HEAD”},“scenery-phet”:{“sha”:“e456b20e808ce3b4a8fd05e080eed351586c5e34”,“branch”:“HEAD”},“sherpa”:{“sha”:“11a029ea6369995dc1bd7e848b144e29944c059d”,“branch”:“HEAD”},“studio”:{“sha”:“dbf2959c7687b35447832c60e981d6cfceb735f3”,“branch”:“HEAD”},“sun”:{“sha”:“ab3bc7c8faaf15e90bceabce4ba42fafb91698f4",“branch”:“HEAD”},“tambo”:{“sha”:“6c459abb011ffea210942ae5113f64f9f97c4cfe”,“branch”:“HEAD”},“tandem”:{“sha”:“e3802f71179aa474379d9a61109ea9f5e6cefbe7",“branch”:“HEAD”},“twixt”:{“sha”:“593074d59e4179caf351cdcc480fd46!
eba5a7140”,“branch”:“HEAD”},“utterance-queue”:{“sha”:“c913734140afa0f7b3923e18234bf06f5e2ea866",“branch”:“HEAD”}}
[7:05](https://phetsims.slack.com/archives/C6HPE0J91/p1649163944993599)
```

**Comment by samreid** [comment]
Here is the chipper acorn issue that is probably related: https://github.com/phetsims/chipper/issues/1171

**Comment by samreid** [comment]
Let's track this in https://github.com/phetsims/chipper/issues/1171, closing.
