### ISSUE TITLE
BUILD ERROR: Could not find Chromium 

### ISSUE THREAD

**Issue by mattpen** [phetsims/perennial#293]
This problem caused 13 failures last night:

```
Build failure: Error: Build aborted, Error: Could not find Chromium (rev. 1056772). This can occur if either
 1. you did not perform an installation before running the script (e.g. `npm install`) or
 2. your cache path is incorrectly configured (which is: /home/phet-admin/.cache/puppeteer).
For (2), check out our guide on configuring puppeteer at https://pptr.dev/guides/configuration.. Sim = graphing-quadratics Version = 1.2.4 Brands = phet,phet-io Locales = * Shas = {"comment":"# graphing-quadratics 1.2.4 Mon Dec 12 2022 22:08:16 GMT-0700 (Mountain Standard Time)","assert":{"sha":"f360fa1bd09a47b3c9e49cd90c8dddd136a13e0c","branch":"HEAD"},"axon":{"sha":"d09f8f50b1a8b97145612bece9e7d91a20e05b28","branch":"HEAD"},"brand":{"sha":"0c723e76a7bad4344cb588c486ae41d0f7fc4995","branch":"HEAD"},"chipper":{"sha":"dc19b10058d77fa37994d46ef87948efd9c8840c","branch":"HEAD"},"dot":{"sha":"aacdd9db44ef332395aa95b0b134b6032d5b8a59","branch":"HEAD"},"graphing-lines":{"sha":"7bc6a8269b9571a7788bee67edb62642f9f28770","branch":"HEAD"},"graphing-quadratics":{"sha":"858fb73577fe06b4f001e5010e53377b4e4deb83","branch":"1.2"},"joist":{"sha":"c9e0651691f92300b205a3f023f0fa425ecf72cd","branch":"HEAD"},"kite":{"sha":"a5a45cba30bc83d0400d83f03c7e4ffe06d75501","branch":"HEAD"},"perennial-alias":{"sha":"f8bc290d1f540479ca66394adfa681158a18e720","branch":"HEAD"},"phet-core":{"sha":"d463e28b571c2df13af9e3db60f741f1457b8ff2","branch":"HEAD"},"phet-io":{"sha":"5ff1615454c98ae6bf43ccb9149ec17282d66c70","branch":"HEAD"},"phet-io-client-guides":{"sha":"1a588f974609e9665b4bdeb6c839762b7a60a4fd","branch":"HEAD"},"phet-io-wrappers":{"sha":"dd9755228f1eff6bd01448d2c6825f2e1471fcbc","branch":"HEAD"},"phetcommon":{"sha":"702911858bafc8e772a2b9d8747ef599cc2bce5c","branch":"HEAD"},"phetmarks":{"sha":"589cdbe7c499adfc1cc478b11340fc0ac61ff93d","branch":"HEAD"},"query-string-machine":{"sha":"12cfdab188ee5be9a8c1932411ad41da8b175c88","branch":"HEAD"},"scenery":{"sha":"358871705ac9dcdfb784f5d05636537cff8d5514","branch":"HEAD"},"scenery-phet":{"sha":"ae26d9545906e569103474e35c7bd6f9887107a4","branch":"HEAD"},"sherpa":{"sha":"ec49f43aee29c836c13884be095e2772bc9faaa0","branch":"HEAD"},"studio":{"sha":"6000377b355bd90674414eae4fa4f695dc7fb40b","branch":"HEAD"},"sun":{"sha":"ca4c2fb861e678adc960a84f67b90875eaab3e1c","branch":"HEAD"},"tambo":{"sha":"74283e495d4fe3296060603ae33393464ae4dbd7","branch":"HEAD"},"tandem":{"sha":"dcea61ce3483056a7d4750d3c51aa3f6d20365cd","branch":"HEAD"},"twixt":{"sha":"35e83120131ca1265e72d84c822a21bb557e08cb","branch":"HEAD"},"utterance-queue":{"sha":"c5024988addef3818199c1bad305d4b9c6e1e385","branch":"HEAD"}}
```

Affected sims:
graphing-quadratics
geometric-optics
density
fourier-making-waves
forces-and-motion-basics
equality-explorer
color-vision
collision-lab
circuit-construction-kit-dc-virtual-lab
circuit-construction-kit-dc
circuit-construction-kit-ac-virtual-lab
circuit-construction-kit-ac 
balloons-and-static-electricity

Looks like this also affected faradays-law, but the build-server did not send an email.

@jonathanolson @zepumph - any ideas what went wrong here?

**Comment by mattpen** [comment]
I did a git pull, npm prune, and npm update in perennial on phet-server2 and then restarted the build-server.  I attempted to rebuild balloons-and-static-electricity, but encountered an error on my development machine:

```
[~/phet/git/perennial]$ grunt production --branch=1.5 --repo=balloons-and-static-electricity --brands=phet

...

Fatal error: Perennial task failed:
Error: grunt --brands=phet --locales=en --allHTML --debugHTML in ../balloons-and-static-electricity failed with exit code 1
stdout:
Running "lint-all" task

Running "report-media" task

Running "clean" task

Running "build" task
Building runnable repository (balloons-and-static-electricity, brands: phet)
Building brand: phet
>> Webpack build complete: 3210ms
Fatal error: Perennial task failed:
AssertionError [ERR_ASSERTION]: repo .. missing from package.json's phetLibs for ../../package.json
    at /Users/matt/phet/git/chipper/js/grunt/buildRunnable.js:130:5
    at Array.forEach (<anonymous>)
    at module.exports (/Users/matt/phet/git/chipper/js/grunt/buildRunnable.js:124:29)
    at async /Users/matt/phet/git/chipper/js/grunt/Gruntfile.js:287:11
    at async wrap (/Users/matt/phet/git/chipper/js/grunt/Gruntfile.js:73:7)
Full Error details:
AssertionError [ERR_ASSERTION]: repo .. missing from package.json's phetLibs for ../../package.json

    at ChildProcess.<anonymous> (/Users/matt/phet/git/perennial/js/common/execute.js:89:21)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1091:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:513:28)
    at Pipe.<anonymous> (node:net:313:12)
Full Error details:
Error: grunt --brands=phet --locales=en --allHTML --debugHTML in ../balloons-and-static-electricity failed with exit code 1
stdout:
Running "lint-all" task

Running "report-media" task

Running "clean" task

Running "build" task
Building runnable repository (balloons-and-static-electricity, brands: phet)
Building brand: phet
>> Webpack build complete: 3210ms
Fatal error: Perennial task failed:
AssertionError [ERR_ASSERTION]: repo .. missing from package.json's phetLibs for ../../package.json
    at /Users/matt/phet/git/chipper/js/grunt/buildRunnable.js:130:5
    at Array.forEach (<anonymous>)
    at module.exports (/Users/matt/phet/git/chipper/js/grunt/buildRunnable.js:124:29)
    at async /Users/matt/phet/git/chipper/js/grunt/Gruntfile.js:287:11
    at async wrap (/Users/matt/phet/git/chipper/js/grunt/Gruntfile.js:73:7)
Full Error details:
AssertionError [ERR_ASSERTION]: repo .. missing from package.json's phetLibs for ../../package.json
```

**Comment by mattpen** [comment]
It looks like the things that failed are:

1. screenshots did not get regenerated
2. database did not get notified, so metadata including the version number is stale
3. The sim-name.xml file did not get created, so screen name and title metadata could be stale on the website

**Comment by zepumph** [comment]
@jonathanolson @mattpen and I determined that this would be solved if we apply the changes from https://github.com/phetsims/chipper/issues/114 over to every release branch. We will report back!

**Comment by zepumph** [comment]
Looks like it is working well. Closing
