### ISSUE TITLE
CT Error: No files matching '../scenery-lab-demo' were found.

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/perennial#302]
```
perennial : lint-everything
Lint-everything failed with status code 1:
Running "lint-everything" task
Fatal error: Perennial task failed:
Error: No files matching '../scenery-lab-demo' were found.
at FileEnumerator.iterateFiles (/data/share/phet/continuous-testing/ct-snapshots/1674713901436/chipper/node_modules/eslint/lib/cli-engine/file-enumerator.js:320:27)
at iterateFiles.next (<anonymous>)
at CLIEngine.executeOnFiles (/data/share/phet/continuous-testing/ct-snapshots/1674713901436/chipper/node_modules/eslint/lib/cli-engine/cli-engine.js:786:48)
at ESLint.lintFiles (/data/share/phet/continuous-testing/ct-snapshots/1674713901436/chipper/node_modules/eslint/lib/eslint/eslint.js:551:23)
at lintOneRepo (/data/share/phet/continuous-testing/ct-snapshots/1674713901436/chipper/js/grunt/lint.js:119:32)
at lint (/data/share/phet/continuous-testing/ct-snapshots/1674713901436/chipper/js/grunt/lint.js:169:27)
at processTicksAndRejections (internal/process/task_queues.js:93:5)
at async /data/share/phet/continuous-testing/ct-snapshots/1674713901436/perennial/js/grunt/Gruntfile.js:544:31
at async wrap (/data/share/phet/continuous-testing/ct-snapshots/1674713901436/perennial/js/grunt/Gruntfile.js:44:7)
Full Error details:
Error: No files matching '../scenery-lab-demo' were found.
Snapshot from 1/25/2023, 11:18:21 PM
```

**Comment by mattpen** [comment]
@jonathanolson - do we just need to clone missing repos or something?

**Comment by jonathanolson** [comment]
No need, scenery-lab-demo shouldn't be linted. I believe this was fixed in another commit.
