### ISSUE TITLE
CT Error: Failed to load parser '@babel/eslint-parser' declared in '../rosetta/.eslintrc.cjs': Cannot find module 'eslint/package.json'

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/perennial#305]
```
perennial : lint-everything
Lint-everything failed with status code 1:
Running "lint-everything" task
Fatal error: Perennial task failed:
Error: Failed to load parser '@babel/eslint-parser' declared in '../rosetta/.eslintrc.cjs': Cannot find module 'eslint/package.json'
Require stack:
- /data/share/phet/continuous-testing/ct-snapshots/1675941434104/rosetta/node_modules/@babel/eslint-parser/lib/utils/eslint-version.cjs
- /data/share/phet/continuous-testing/ct-snapshots/1675941434104/rosetta/node_modules/@babel/eslint-parser/lib/convert/convertTokens.cjs
- /data/share/phet/continuous-testing/ct-snapshots/1675941434104/rosetta/node_modules/@babel/eslint-parser/lib/convert/index.cjs
- /data/share/phet/continuous-testing/ct-snapshots/1675941434104/rosetta/node_modules/@babel/eslint-parser/lib/parse.cjs
- /data/share/phet/continuous-testing/ct-snapshots/1675941434104/rosetta/node_modules/@babel/eslint-parser/lib/index.cjs
- /data/share/phet/continuous-testing/ct-snapshots/1675941434104/chipper/node_modules/@eslint/eslintrc/dist/eslintrc.cjs
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
at Function.Module._load (internal/modules/cjs/loader.js:725:27)
at Module.require (internal/modules/cjs/loader.js:952:19)
at require (internal/modules/cjs/helpers.js:88:18)
at Object.<anonymous> (/data/share/phet/continuous-testing/ct-snapshots/1675941434104/rosetta/node_modules/@babel/eslint-parser/lib/utils/eslint-version.cjs:1:27)
at Module._compile (internal/modules/cjs/loader.js:1063:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
at Module.load (internal/modules/cjs/loader.js:928:32)
at Function.Module._load (internal/modules/cjs/loader.js:769:14)
at Module.require (internal/modules/cjs/loader.js:952:19)
Full Error details:
Error: Failed to load parser '@babel/eslint-parser' declared in '../rosetta/.eslintrc.cjs': Cannot find module 'eslint/package.json'
Require stack:
- /data/share/phet/continuous-testing/ct-snapshots/1675941434104/rosetta/node_modules/@babel/eslint-parser/lib/utils/eslint-version.cjs
- /data/share/phet/continuous-testing/ct-snapshots/1675941434104/rosetta/node_modules/@babel/eslint-parser/lib/convert/convertTokens.cjs
- /data/share/phet/continuous-testing/ct-snapshots/1675941434104/rosetta/node_modules/@babel/eslint-parser/lib/convert/index.cjs
- /data/share/phet/continuous-testing/ct-snapshots/1675941434104/rosetta/node_modules/@babel/eslint-parser/lib/parse.cjs
- /data/share/phet/continuous-testing/ct-snapshots/1675941434104/rosetta/node_modules/@babel/eslint-parser/lib/index.cjs
- /data/share/phet/continuous-testing/ct-snapshots/1675941434104/chipper/node_modules/@eslint/eslintrc/dist/eslintrc.cjs
Snapshot from 2/9/2023, 4:17:14 AM
```

**Comment by liammulh** [comment]
I believe this is fixed.
