### ISSUE TITLE
Error spawn EINVAL when running grunt --brands=adapted-from-phet in the final step of documentation

### ISSUE THREAD

**Issue by WajahatKanju** [phetsims/perennial#357]
**Description**:
Following the steps outlined in the documentation under "Quick Start," I encountered an error at the final step when running grunt --brands=adapted-from-phet. The error details are as follows:
`Running "lint-all" task
[                                        ] 0.00%Error running ESLint: spawn EINVAL
Fatal error: Perennial task failed:
Error: spawn EINVAL
    at ChildProcess.spawn (node:internal/child_process:421:11)
    at spawn (node:child_process:761:9)
    at D:\Desktop\tes\chipper\js\grunt\lint.js:121:20
    at new Promise (<anonymous>)
    at runEslint (D:\Desktop\tes\chipper\js\grunt\lint.js:105:10)
    at lint (D:\Desktop\tes\chipper\js\grunt\lint.js:186:27)
    at D:\Desktop\tes\chipper\js\grunt\Gruntfile.js:360:35
    at Object.<anonymous> (D:\Desktop\tes\chipper\js\grunt\Gruntfile.js:92:13)
    at thisTask.fn (D:\Desktop\tes\example-sim\node_modules\grunt\lib\grunt\task.js:70:16)
    at Object.<anonymous> (D:\Desktop\tes\example-sim\node_modules\grunt\lib\util\task.js:294:30)
`
Steps to Reproduce:
1. Clone the necessary repositories:
`git clone https://github.com/phetsims/assert.git
git clone https://github.com/phetsims/axon.git
git clone https://github.com/phetsims/babel.git
git clone https://github.com/phetsims/brand.git
git clone https://github.com/phetsims/chipper.git
git clone https://github.com/phetsims/dot.git
git clone https://github.com/phetsims/example-sim.git
git clone https://github.com/phetsims/joist.git
git clone https://github.com/phetsims/kite.git
git clone https://github.com/phetsims/perennial.git perennial-alias
git clone https://github.com/phetsims/phet-core.git
git clone https://github.com/phetsims/phetcommon.git
git clone https://github.com/phetsims/phetmarks.git
git clone https://github.com/phetsims/query-string-machine.git
git clone https://github.com/phetsims/scenery.git
git clone https://github.com/phetsims/scenery-phet.git
git clone https://github.com/phetsims/sherpa.git
git clone https://github.com/phetsims/sun.git
git clone https://github.com/phetsims/tambo.git
git clone https://github.com/phetsims/tandem.git
git clone https://github.com/phetsims/twixt.git
git clone https://github.com/phetsims/utterance-queue.git
`
2. Install development dependencies:
`cd chipper
npm install
cd ../perennial-alias
npm install
cd ../example-sim
npm install
`
3.Transpile the code:
`cd ../chipper/
node js/scripts/transpile.js --watch
`
4. Start an HTTP server in a new terminal/command prompt.
5. Open the simulation in the browser: http://localhost/example-sim/example-sim_en.html.
6. Build the simulation:
`
cd ../example-sim
grunt --brands=adapted-from-phet
`

**Expected Behavior:**
The simulation should build without errors.

**Actual Behavior:**
The process fails with the following error:

`Error running ESLint: spawn EINVAL
Fatal error: Perennial task failed:
Error: spawn EINVAL
`

**Comment by zepumph** [comment]
Thank you for the thorough report. I will look into this. In the mean time, can you add `--lint=false` to the grunt command. It should get around this problem for a build to help get you started.

**Comment by fgamador** [comment]
This may be related to #359, which has a recommended fix.

**Comment by zepumph** [comment]
Yes thanks, fix will be committed over in https://github.com/phetsims/perennial/issues/359

**Comment by WajahatKanju** [comment]
@zepumph  if you can guide me. I am wiling to fix

**Comment by zepumph** [comment]
@WajahatKanju, I believe that everything has been fixed. Can you please `git pull` in `perennial-alias` and `chipper`, and see if things are working for you now?
