### ISSUE TITLE
Failed build for molecule-shapes-basics RC

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/perennial#7]
The changes to inspect the .xml to see what translations were previously deployed also seems to have broken this particular case. The file in question (/data/web/htdocs/phetsims/sims/html/molecule-shapes-basics/1.0.0-dev.5/molecule-shapes-basics.xml) does NOT exist, as it was deployed a long time ago.

```
2016-01-14T22:08:56.730Z - info: detecting version number: 1.1.0-rc.2
2016-01-14T22:08:56.730Z - info: building sim molecule-shapes-basics
2016-01-14T22:08:56.731Z - info: wrote file ./js/build-server/tmp/dependencies.json
2016-01-14T22:08:56.731Z - info: running command: git pull
2016-01-14T22:08:57.009Z - info: git pull ran successfully in directory: .
2016-01-14T22:08:57.009Z - info: running command: npm install
2016-01-14T22:08:58.920Z - info: npm install ran successfully in directory: .
2016-01-14T22:08:58.920Z - info: running command: ./chipper/bin/clone-missing-repos.sh
2016-01-14T22:08:58.945Z - info: ./chipper/bin/clone-missing-repos.sh ran successfully in directory: ..
2016-01-14T22:08:58.946Z - info: pulling from assert
2016-01-14T22:08:58.954Z - info: pulling from axon
2016-01-14T22:08:58.961Z - info: pulling from brand
2016-01-14T22:08:58.966Z - info: pulling from chipper
2016-01-14T22:08:58.969Z - info: pulling from dot
2016-01-14T22:08:58.973Z - info: pulling from joist
2016-01-14T22:08:58.978Z - info: pulling from kite
2016-01-14T22:08:58.984Z - info: pulling from molecule-shapes
2016-01-14T22:08:58.989Z - info: pulling from molecule-shapes-basics
2016-01-14T22:08:58.996Z - info: pulling from nitroglycerin
2016-01-14T22:08:59.001Z - info: pulling from phet-core
2016-01-14T22:08:59.006Z - info: pulling from phetcommon
2016-01-14T22:08:59.019Z - info: pulling from scenery
2016-01-14T22:08:59.024Z - info: pulling from scenery-phet
2016-01-14T22:08:59.028Z - info: pulling from sherpa
2016-01-14T22:08:59.031Z - info: pulling from sun
2016-01-14T22:08:59.034Z - info: pulling from tandem
2016-01-14T22:08:59.560Z - info: running command: grunt checkout-shas --buildServer=true --repo=molecule-shapes-basics
2016-01-14T22:09:00.179Z - info: grunt checkout-shas --buildServer=true --repo=molecule-shapes-basics ran successfully in directory: .
2016-01-14T22:09:00.179Z - info: running command: git checkout 199cd6ef219cb9776231e28ab7a812a6984029db
2016-01-14T22:09:00.190Z - info: git checkout 199cd6ef219cb9776231e28ab7a812a6984029db ran successfully in directory: ../molecule-shapes-basics
2016-01-14T22:09:00.190Z - info: running command: npm install
2016-01-14T22:09:01.456Z - info: npm install ran successfully in directory: ../chipper
2016-01-14T22:09:01.456Z - info: running command: npm install
2016-01-14T22:09:15.931Z - info: npm install ran successfully in directory: ../molecule-shapes-basics

fs.js:438
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory '/data/web/htdocs/phetsims/sims/html/molecule-shapes-basics/1.0.0-dev.5/molecule-shapes-basics.xml'
    at Object.fs.openSync (fs.js:438:18)
    at Object.fs.readFileSync (fs.js:289:15)
    at getLocales (/data/share/phet/phet-repos/perennial/js/build-server/build-server.js:451:28)
    at /data/share/phet/phet-repos/perennial/js/build-server/build-server.js:818:25
    at /data/share/phet/phet-repos/perennial/js/build-server/build-server.js:288:27
    at ChildProcess.exithandler (child_process.js:646:7)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:756:16)
    at Socket.<anonymous> (child_process.js:969:11)
    at Socket.emit (events.js:95:17)
```

**Comment by jonathanolson** [comment]
Looks like the files.sort()[ files.length - 1 ]; is picking out the wrong directory (1.0.0 is newer than 1.0.0-dev.5).

**Comment by jonathanolson** [comment]
Duplicate of https://github.com/phetsims/perennial/issues/28 (there is more information there, so closing here).
