### ISSUE TITLE
writePhetioHtaccess is failing for chipper 1.0 builds

### ISSUE THREAD

**Issue by mattpen** [phetsims/perennial#84]
```Feb 27 21:06:28 phet-server.int.colorado.edu build-server[127605]: debug: stdout:
Feb 27 21:06:28 phet-server.int.colorado.edu build-server[127605]: Done.
Feb 27 21:06:28 phet-server.int.colorado.edu build-server[127605]: debug: deploying to servers: [“production”]
Feb 27 21:06:28 phet-server.int.colorado.edu build-server[127605]: info: deploying to production
Feb 27 21:06:28 phet-server.int.colorado.edu build-server[127605]: error:  Error
Feb 27 21:06:28 phet-server.int.colorado.edu build-server[127605]: at Object.fs.openSync (fs.js:646:18)
Feb 27 21:06:28 phet-server.int.colorado.edu build-server[127605]: at Object.fs.writeFileSync (fs.js:1291:33)
Feb 27 21:06:28 phet-server.int.colorado.edu build-server[127605]: at module.exports (/data/share/phet/phet-repos/perennial/js/build-server/writeFile.
Feb 27 21:06:28 phet-server.int.colorado.edu build-server[127605]: at writePhetioHtaccess (/data/share/phet/phet-repos/perennial/js/build-server/write
Feb 27 21:06:28 phet-server.int.colorado.edu build-server[127605]: at taskWorker (/data/share/phet/phet-repos/perennial/js/build-server/taskWorker.js:
Feb 27 21:06:28 phet-server.int.colorado.edu build-server[127605]: at <anonymous>
Feb 27 21:06:28 phet-server.int.colorado.edu build-server[127605]: at process._tickCallback (internal/process/next_tick.js:188:7)
Feb 27 21:06:28 phet-server.int.colorado.edu build-server[127605]: info: Error writing /data/web/static/phet-io/sims/john-travoltage/1.4.3-phetio/wrap
Feb 27 21:06:28 phet-server.int.colorado.edu build-server[127605]: error:  Error
Feb 27 21:06:28 phet-server.int.colorado.edu build-server[127605]: at Object.fs.openSync (fs.js:646:18)
Feb 27 21:06:28 phet-server.int.colorado.edu build-server[127605]: at Object.fs.writeFileSync (fs.js:1291:33)
Feb 27 21:06:28 phet-server.int.colorado.edu build-server[127605]: at module.exports (/data/share/phet/phet-repos/perennial/js/build-server/writeFile.
Feb 27 21:06:28 phet-server.int.colorado.edu build-server[127605]: at writePhetioHtaccess (/data/share/phet/phet-repos/perennial/js/build-server/write
Feb 27 21:06:28 phet-server.int.colorado.edu build-server[127605]: at taskWorker (/data/share/phet/phet-repos/perennial/js/build-server/taskWorker.js:
Feb 27 21:06:28 phet-server.int.colorado.edu build-server[127605]: at <anonymous>```

**Comment by mattpen** [comment]
This should be working now, it was fixed as part of #87
